### PR TITLE
👩‍🌾 [backport] [foxy] Update cmake minimum version to 2.8.12 (#61)

### PR DESCRIPTION
**Pull request by chapulina**
Backporting #61 to fix the warning on Foxy.

---

https://github.com/osrf/buildfarmer/issues/181

### CODE REVIEW

**Comment by chapulina** [comment]
I'll trigger CI after Jenkins is reset at ci.ros2.org

**Comment by chapulina** [comment]
CI is running, I used a repos file generated with [make_repos_gist](https://github.com/sloretz/scripts-and-stuff/tree/master/make_repos_gist) and it's testing up to `rcutils` like the original PR.

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/14437/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/9209/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/12109/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/14539/)

**Comment by chapulina** [comment]
The farm was in a bad state yesterday. New run:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/14440/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/9211/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/12111/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/14541/)

**Comment by wjwwood** [comment]
CI again since the cyclonedds issue was resolved:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/14448/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/9219/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/12119/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/14552/)

**Comment by chapulina** [comment]
Also needed a fix from https://github.com/osrf/osrf_testing_tools_cpp/pull/55, done in 1ff09bc.

New round of CI:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/14457/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/9227/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/12128/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/14559/)

**Comment by chapulina** [comment]
Oh look at that, not only this warning is gone, but all other Windows warnings are gone too :thinking: Fishy :fish: 

It looks like it did what this PR was set to do:

```
18:28:17 -- googletest version '1.10.0.1' selected, of versions: '1.8.1;1.10.0.1'
18:28:17 -- building googletest from 'C:/ci/ws/src/osrf/osrf_testing_tools_cpp/osrf_testing_tools_cpp/vendor/google/googletest/release-1.10.0.1.tar.gz'...
```

**Pull request merged**
