### PR TITLE
Initial support for Apple M1

### PR DESCRIPTION
**Pull request by eboasson**
Signed-off-by: Erik Boasson <eb@ilities.com>

### CODE REVIEW

**Comment by clalancette** [comment]
It looks like this is being done in a slightly different way upstream: https://github.com/bombela/backward-cpp/pull/201

I think we should probably comment on that one and push to get it landed, and then update our vendored copy here.

**Comment by eboasson** [comment]
I've asked them

**Comment by christophebedard** [comment]
The upstream PR was merged: https://github.com/bombela/backward-cpp/pull/201.

@clalancette I know this will have to wait until a `galactic` branch is created, but how should the vendor copy be updated? We're currently using `v1.5` (#45) + an additional fix (#54), but there is no newer release (`>=v1.6`). Should I just use the latest `master` commit or should I use the commit corresponding to https://github.com/bombela/backward-cpp/pull/201?

**Comment by clalancette** [comment]
> @clalancette I know this will have to wait until a `galactic` branch is created, but how should the vendor copy be updated? We're currently using `v1.5` (#45) + an additional fix (#54), but there is no newer release (`>=v1.6`). Should I just use the latest `master` commit or should I use the commit corresponding to [bombela/backward-cpp#201](https://github.com/bombela/backward-cpp/pull/201)?

I'd personally go with the latest master commit.

**Comment by clalancette** [comment]
Actually, this should just be closed in favor of #64, so I'll do that now.

**Pull request closed without merging**
