### PR TITLE
Update CMakeLists.txt

### PR DESCRIPTION
**Pull request by mosfet80**
Use the same GTE version used into 

https://github.com/osrf/osrf_testing_tools_cpp/blob/rolling/osrf_testing_tools_cpp/CMakeLists.txt

removed old googletest lib

### CODE REVIEW

**Review by clalancette — CHANGES_REQUESTED** [review]
While I agree with updating the version here, the only way this will work is if we also update the tarball that corresponds to it.  That is, we need to add a *new* tarball here that contains googletest 1.14.

**Comment by mosfet80** [comment]
> While I agree with updating the version here, the only way this will work is if we also update the tarball that corresponds to it. That is, we need to add a _new_ tarball here that contains googletest 1.14.

test_osrf_testing_tools_cpp and osrf_testing_tools_cpp used two different versions of googletest.

The googletest version 1.14 file was already in the folder.

https://github.com/osrf/osrf_testing_tools_cpp/blob/rolling/osrf_testing_tools_cpp/vendor/google/googletest/release-1.14.0.tar.gz

**Comment by clalancette** [comment]
> test_osrf_testing_tools_cpp and osrf_testing_tools_cpp used two different versions of googletest.

Ah!  Thanks for the explanation.  Will take a closer look.

**Review by clalancette — APPROVED** [review]
This looks good to me, thanks for the cleanup.  I'll run CI on it next.

**Comment by clalancette** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/20968/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/15266/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/21646/)

**Pull request merged**
