### PR TITLE
Update backward-cpp to latest master commit

### PR DESCRIPTION
**Pull request by christophebedard**
Supersedes #62

This updates https://github.com/bombela/backward-cpp to the latest `master` commit to support Apple M1 processors.

To make the changes explicit, I first reverted the changes that were made on top of the subtree: https://github.com/osrf/osrf_testing_tools_cpp/commit/5baf4f64a8fa3c7c1ac69b2bfe05051e128f8526, a "squash revert" of https://github.com/osrf/osrf_testing_tools_cpp/commit/ae8e0f54ec446d108405b0044891d867479384af and https://github.com/osrf/osrf_testing_tools_cpp/commit/4404ea5eaa2288c1348baaf4b7d4233a70326133.

Then I removed the directory and re-added it, pointing to the latest release, `v1.6`: https://github.com/bombela/backward-cpp/tree/v1.6.

Then I re-applied a local fix: https://github.com/osrf/osrf_testing_tools_cpp/commit/6419f3cd7b23465128f0aea24756154f3971d25f. The upstream code changed a bit and I don't think the other fix (https://github.com/osrf/osrf_testing_tools_cpp/commit/4404ea5eaa2288c1348baaf4b7d4233a70326133) is needed now. CI will hopefully confirm.

As part of this update, I submitted a few PRs to fix building on M1 + some warnings: https://github.com/bombela/backward-cpp/pull/211, https://github.com/bombela/backward-cpp/pull/212, https://github.com/bombela/backward-cpp/pull/213.

Signed-off-by: Christophe Bedard <bedard.christophe@gmail.com>

### CODE REVIEW

**Comment by christophebedard** [comment]
My fix (https://github.com/bombela/backward-cpp/pull/213) has just been merged, but since other things have been merged as well I will have to test it on macOS before updating this to point to the latest `master` commit again.

**Comment by wjwwood** [comment]
> My fix (bombela/backward-cpp#213) has just been merged, but since other things have been merged as well I will have to test it on macOS before updating this to point to the latest master commit again.

Cool, thanks for the update. Let me know when you've tested it. I still don't have an M1 device to test these things.

> Then I removed the directory and re-added it, pointing to the latest commit on master, since there is no newer release: bombela/backward-cpp@51822c8.

Do you think they'll be making any releases soon? Maybe we should ask? I'm not opposed to picking a commit hash, but on the other hand, a version would be nice.

**Comment by christophebedard** [comment]
Tested it and it seems to be working. Well, it builds.

> Do you think they'll be making any releases soon? Maybe we should ask? I'm not opposed to picking a commit hash, but on the other hand, a version would be nice.

Not sure, but yeah they might if we ask. However, I feel like this kind of dependency can break so easily given the number of different platforms/architectures we usually want to support, so picking a commit and sticking to it might be a more stable/safe solution.

Updating the commit hash is a bit of a pain though! It's up to you, I can ask for a new version/tag.

**Comment by christophebedard** [comment]
@wjwwood friendly ping

**Comment by wjwwood** [comment]
@christophebedard I'll try to get to this next week. Did you ask for a new version? Or has one come out in the meantime?

**Comment by christophebedard** [comment]
> @christophebedard I'll try to get to this next week. Did you ask for a new version? Or has one come out in the meantime?

I didn't ask, and there doesn't seem to be a new version. There are some new commits though. I'd have to test it again, and I'm just afraid it's going to break again if we track a possibly moving tag.

**Comment by wjwwood** [comment]
> if we track a possibly moving tag.

Tags shouldn't move...

But if there's no newer version then that's fine.

**Comment by wjwwood** [comment]
I asked https://github.com/bombela/backward-cpp/issues/233

Either way I'll move forward on this next week.

**Comment by wjwwood** [comment]
Ok, 1.6 is now an option. I'll update this pr to that next week, unless someone beats me to it.

**Comment by christophebedard** [comment]
@wjwwood I re-did the steps on `master` to get backward-cpp@v1.6.

`test_osrf_testing_tools_cpp` and `osrf_testing_tools_cpp` build fine and the tests pass.

**Comment by wjwwood** [comment]
CI:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/15574/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/10258/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/13242/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/15794/)

**Comment by christophebedard** [comment]
The Linux-aarch64 failure seems to be unrelated, but I can't find any recent jobs with the same failure. Let's try re-running it just to see:

* Linux-aarch64 [Build Status](https://ci.ros2.org/job/ci_linux-aarch64/10259/)

**Comment by wjwwood** [comment]
Thanks for following through on this @christophebedard, sorry I didn't get to it before you.

**Pull request merged**
